In [1]:
#import libraries
import os
import sys
import numpy as np
import pandas as pd

In [3]:
climate_plan = pd.read_csv(os.path.join('..','..','data','raw','lgcap_survey_raw_data.csv'))

In [5]:
climate_plan.head()

,Year,Org Unit,MUNI,RD,EDR,1: FTEs,2: Climate Action Plan,"2: addressing mitigation, adaptation and/or energy use",2: addressing mitigation and adaptation,2: addressing mitigation and energy,...,20: LGCAP funding for year one- Reserve funding (2),20: LGCAP funding for year one-Reserve funding - No decision has been made.,21: Additional funding leveraged,22: total mitigation investment,23: expected co2e reductions,24: total investment in adaptation and resilience,25: use a climate lens on infrastructure planning and decision-making?,2020 pop,Size,GEO
0,2022,5941005,100 Mile House,Cariboo Regional District,Cariboo,0.25,Yes,NaN,NaN,NaN,...,NaN,No decision has been made.,0.0,0.0,NaN,0.00,No,1881,Small,"100 Mile House, British Columbia, Canada"
1,2022,5909052,Abbotsford,Fraser Valley Regional District,Mainland/Southwest,5.50,No,NaN,NaN,NaN,...,NaN,No decision has been made.,9100000.0,1173563.0,0.0,3350077.63,No,161581,Large,"Abbotsford, British Columbia, Canada"
2,2022,1005923,Alberni-Clayoquot Regional District,Alberni-Clayoquot Regional District,Vancouver Island/Coast,0.50,No,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,NaN,0.00,No,10362,Small,"Alberni-Clayoquot Regional District, British C..."
3,2022,5943008,Alert Bay,Mount Waddington Regional District,Vancouver Island/Coast,0.10,No,NaN,NaN,NaN,...,NaN,No decision has been made.,0.0,0.0,NaN,0.00,No,441,Small,"Alert Bay, British Columbia, Canada"
4,2022,5915038,Anmore,Metro Vancouver Regional District,Mainland/Southwest,0.00,No,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,0.00,No,2412,Small,"Anmore, British Columbia, Canada"

In [7]:
# Create a mapping dictionary for community name standardization
community_name_mapping = {
    'Langley, City of': 'Langley City',
    'Langley, District Municipality': 'Langley Township',
    'North Vancouver, City of': 'North Vancouver City',
    'North Vancouver, District Municipality': 'North Vancouver District',
    '100 Mile House': 'One Hundred Mile House',
    'Daajing Giids': 'Queen Charlotte',
    'Sechelt District Municipality': 'Sechelt'
}

# Apply the mapping to the MUNI column
climate_plan['MUNI'] = climate_plan['MUNI'].replace(community_name_mapping)

In [4]:
# Get community names used in the wellbeing dataset to match with remoteness dataset
wellbeing_communities = pd.read_csv(os.path.join('..','..','data','processed','matched_cwb_2021.csv'), usecols=['CSD Name 2021'])

In [8]:
# Get unique community names from each dataset as a list
climate_plan_communities = set(climate_plan['MUNI'].dropna())

# Find exact matches (as a list)
exact_matches_2021 = climate_plan_communities.intersection(set(wellbeing_communities['CSD Name 2021']))

print(f"Exact matches with 2021 wellbeing: {len(exact_matches_2021)}")

# Get unmatched communities by subtracting lists
unmatched_communities = set(wellbeing_communities['CSD Name 2021']) - exact_matches_2021

print("\nAll unmatched communities:")
for community in sorted(list(unmatched_communities)):
    print(f"  {community}")

Exact matches with 2021 wellbeing: 145

All unmatched communities:

In [9]:
climate_plan_subset = climate_plan[climate_plan['MUNI'].isin(exact_matches_2021)].copy()

In [10]:
climate_plan_subset.head()

,Year,Org Unit,MUNI,RD,EDR,1: FTEs,2: Climate Action Plan,"2: addressing mitigation, adaptation and/or energy use",2: addressing mitigation and adaptation,2: addressing mitigation and energy,...,20: LGCAP funding for year one- Reserve funding (2),20: LGCAP funding for year one-Reserve funding - No decision has been made.,21: Additional funding leveraged,22: total mitigation investment,23: expected co2e reductions,24: total investment in adaptation and resilience,25: use a climate lens on infrastructure planning and decision-making?,2020 pop,Size,GEO
0,2022,5941005,One Hundred Mile House,Cariboo Regional District,Cariboo,0.25,Yes,NaN,NaN,NaN,...,NaN,No decision has been made.,0.0,0.0,NaN,0.00,No,1881,Small,"100 Mile House, British Columbia, Canada"
1,2022,5909052,Abbotsford,Fraser Valley Regional District,Mainland/Southwest,5.50,No,NaN,NaN,NaN,...,NaN,No decision has been made.,9100000.0,1173563.0,0.0,3350077.63,No,161581,Large,"Abbotsford, British Columbia, Canada"
3,2022,5943008,Alert Bay,Mount Waddington Regional District,Vancouver Island/Coast,0.10,No,NaN,NaN,NaN,...,NaN,No decision has been made.,0.0,0.0,NaN,0.00,No,441,Small,"Alert Bay, British Columbia, Canada"
4,2022,5915038,Anmore,Metro Vancouver Regional District,Mainland/Southwest,0.00,No,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,0.00,No,2412,Small,"Anmore, British Columbia, Canada"
5,2022,5937028,Armstrong,North Okanagan Regional District,Thompson/Okanagan,0.00,No,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,0.00,No,5433,Small,"Armstrong, British Columbia, Canada"