In [1]:
#import libraries
import os
import sys
import numpy as np
import pandas as pd

In [2]:
climate_plan = pd.read_csv(os.path.join('..','..','data','raw','lgcap_survey_raw_data.csv'))

In [3]:
climate_plan.head()

,Year,Org Unit,MUNI,RD,EDR,1: FTEs,2: Climate Action Plan,"2: addressing mitigation, adaptation and/or energy use",2: addressing mitigation and adaptation,2: addressing mitigation and energy,...,20: LGCAP funding for year one- Reserve funding (2),20: LGCAP funding for year one-Reserve funding - No decision has been made.,21: Additional funding leveraged,22: total mitigation investment,23: expected co2e reductions,24: total investment in adaptation and resilience,25: use a climate lens on infrastructure planning and decision-making?,2020 pop,Size,GEO
0,2022,5941005,100 Mile House,Cariboo Regional District,Cariboo,0.25,Yes,NaN,NaN,NaN,...,NaN,No decision has been made.,0.0,0.0,NaN,0.00,No,1881,Small,"100 Mile House, British Columbia, Canada"
1,2022,5909052,Abbotsford,Fraser Valley Regional District,Mainland/Southwest,5.50,No,NaN,NaN,NaN,...,NaN,No decision has been made.,9100000.0,1173563.0,0.0,3350077.63,No,161581,Large,"Abbotsford, British Columbia, Canada"
2,2022,1005923,Alberni-Clayoquot Regional District,Alberni-Clayoquot Regional District,Vancouver Island/Coast,0.50,No,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,NaN,0.00,No,10362,Small,"Alberni-Clayoquot Regional District, British C..."
3,2022,5943008,Alert Bay,Mount Waddington Regional District,Vancouver Island/Coast,0.10,No,NaN,NaN,NaN,...,NaN,No decision has been made.,0.0,0.0,NaN,0.00,No,441,Small,"Alert Bay, British Columbia, Canada"
4,2022,5915038,Anmore,Metro Vancouver Regional District,Mainland/Southwest,0.00,No,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,0.00,No,2412,Small,"Anmore, British Columbia, Canada"

In [4]:
# Create a mapping dictionary for community name standardization
community_name_mapping = {
    'Langley, City of': 'Langley City',
    'Langley, District Municipality': 'Langley Township',
    'North Vancouver, City of': 'North Vancouver City',
    'North Vancouver, District Municipality': 'North Vancouver District',
    '100 Mile House': 'One Hundred Mile House',
    'Daajing Giids': 'Queen Charlotte',
    'Sechelt District Municipality': 'Sechelt'
}

# Apply the mapping to the MUNI column
climate_plan['MUNI'] = climate_plan['MUNI'].replace(community_name_mapping)

In [5]:
# Get community names used in the wellbeing dataset to match with remoteness dataset
wellbeing_communities = pd.read_csv(os.path.join('..','..','data','processed','matched_cwb_2021.csv'), usecols=['CSD Name 2021'])

In [6]:
# Get unique community names from each dataset as a list
climate_plan_communities = set(climate_plan['MUNI'].dropna())

# Find exact matches (as a list)
exact_matches_2021 = climate_plan_communities.intersection(set(wellbeing_communities['CSD Name 2021']))

print(f"Exact matches with 2021 wellbeing: {len(exact_matches_2021)}")

# Get unmatched communities by subtracting lists
unmatched_communities = set(wellbeing_communities['CSD Name 2021']) - exact_matches_2021

print("\nAll unmatched communities:")
for community in sorted(list(unmatched_communities)):
    print(f"  {community}")

Exact matches with 2021 wellbeing: 147

All unmatched communities:

In [7]:
climate_plan_subset = climate_plan[climate_plan['MUNI'].isin(exact_matches_2021)].copy()

In [8]:
print(climate_plan_subset.columns.tolist())

['Year', 'Org Unit', 'MUNI', 'RD', 'EDR', '1: FTEs', '2:\xa0Climate Action Plan', '2: addressing mitigation, adaptation and/or energy use', '2: addressing mitigation and adaptation', '2: addressing mitigation and energy', '2: addressing adaptation and energy', '2: Standalone mitigation plan', '2: Standalone adaptation plan', '2: Standalone energy-related plan', "2: Don't know", 'Please include a link to the document or webpage if available.', '2: No, but we are currently undertaking one and it will be completed in the next two years.', '2: No, we are not intending to undertake one due to lack of financial capacity.', '2: No, we are not intending to undertake one due to lack of expertise or technical capacity.', '3: climate emergency', '4: Challenges.Lack of jurisdiction.', '4: Challenges.Lack of staff capacity or expertise.', '4: Challenges.Lack of financial resources.', '4: Challenges.Lack of data or information.', '4: Challenges.Lack of local political support.', '4: Challenges.Lack of provincial or federal government support or collaboration.', '4: Challenges.Other.', '4: Challenges.Other. (2)', '5: reported corporate GHG emissions', '5: No, but for a past year. (Please enter most recent year completed: YYYY)', '5: directly delivered services (tCO2e)', '5: contracted services (tCO2e)', '5: total corporate GHG emissions', '5: facilities', '5: mobile sources.\xa0', 'Please provide the link to the public report if available.', '5: No, due to lack of staff and technical capacity.', '5: No, due to lack of financial resources.', '5: No, due to lack of awareness regarding which GHG accounting tools are available.', '5: No, corporate emissions are measured but not reported.', '5: Measurement is in-progress.', '5: Corporate inventory is not developed annually.\xa0', '6: community-wide GHG emissions', '6: transportation sector emissions in tonnes of CO2e for 2022.', '6: community-wide buildings sector emissions in tonnes of CO2e for 2022.', '6: community-wide solid waste sector emissions in tonnes of CO2e for 2022.', '6: No, community GHG emissions were not reported because the 2022 Provincial Community Energy and Emissions Inventory data has not been released.', '6: No, community GHG emissions were not reported because the 2022 Provincial Community Energy and Emissions Inventory does not report transportation data.', '6: No, we do not measure and report community-wide emissions data due to lack of financial capacity.', '6: No, we do not measure and report community-wide emissions data due to lack of staff and technical capacity.', '6: No, we do not measure and report community-wide emissions annually.', '6: No, we do not measure and report community-wide emissions annually (2)', '6: measured and reported community-wide emissions in the past?', 'When was the last year your community or Nation reported its community-wide emissions and what is the interval for reporting (ex. every 5 years)?', 'For the 2022 calendar year, did your community use raw data from the Community Energy and Emissions Inventory initiative to calculate community-wide emissions?', '7: target(s) 2030 Reduction  (format: e.g., 40%)\xa0', '7: target(s).2030 Baseline Year  (format: 2007)', '7: target(s).2040Reduction  (format: e.g., 40%)\xa0', "Question 7: Currently, the Province's legislated GHG emission reduction targets are 40% by 2030, 60% by 2040 and 80% by 2050, relative to 2007. Please state your local government or Nation’s target(s).2040Baseline Year  (format: 2007)", '7: target(s).2050Reduction  (format: e.g., 40%)\xa0', "Question 7: Currently, the Province's legislated GHG emission reduction targets are 40% by 2030, 60% by 2040 and 80% by 2050, relative to 2007. Please state your local government or Nation’s target(s).2050Baseline Year  (format: 2007)", '7: target open years', '8: net-zero or carbon-neutral emissions target?', '9: Supporting Indicators -Private dwellings by structural type', '9: Supporting Indicators - Floor area: Average floor area by building category and era', '9: Supporting Indicators - Residential density: Population and dwelling units per "net" land area', '9: Supporting Indicators -Commute by mode: Employed labour force by mode of commute', '9: Supporting Indicators - Greenspace: Land area that is parks and protected greenspace', '9: Supporting Indicators - Walk score: Proximity to services', '9: Supporting Indicators - Proximity to transit: Persons, dwelling units and employment within walking distance of a "quality" transit stop/line', '9: Supporting Indicators - Other', '9: Supporting Indicators - Other (2)', 'Optional: Please provide any further comments you wish to share on community-wide emissions measurement and reporting here.', '10: Buildings- Zero-carbon new construction', '10: Buildings- Highest efficiency standards for new space and water heating equipment', '10: Buildings- Topping up Provincial energy efficiency programs', '10: Buildings- Step Code adoption', '10: Buildings- Zero Carbon Step Code', '10: Buildings- Zero-carbon heating requirement', '10: Buildings- Net zero buildings commitments', '10: Buildings- Efficiency upgrades to public buildings', '10: Buildings- Demand-side management\xa0', '10: Buildings- Not applicable', '10: Buildings- Other', '10: Buildings- Other (2)', 'Please enter date effective for zero-carbon new construction requirement.', '11: Transportation-Demand-side management to reduce distance travelled (single-occupancy vehicle commute reduction programs, parking disincentives)', '11: Transportation-Improving or expanding public transportation', '11: Transportation-Mode shift targets in Official Community Plan, Regional Growth Strategy or other guiding document', '11: Transportation-Established personal transportation target goals, and measures to reach them, in annual reports – must include target goals for vehicle kilometre reduction, mode share for active transportation and zero-emission vehicles – and report on progress', '11: Transportation-Established commercial transportation target goals, and measures to reach them, in annual reports – must include target goals for vehicle kilometre reduction, mode share for energy efficient commercial transportation and zero-emission vehicles – report on progress', '11: Transportation-Implemented zero-emission vehicle first procurement policy for all local government on and off-road vehicles purchases.', '11: Transportation-Implemented a zero-emission vehicle preference or requirement for contracted work from a service provider', '11: Transportation-Bylaws updated to prioritize energy efficient transportation hierarchy (i.e. pedestrians first)\xa0', '11: Transportation-Revising existing bylaws or implementing new ones to support active transportation', '11: Transportation-Active transportation planning', '11: Transportation-Active transportation infrastructure investments', '11: Transportation-Electric vehicle charging studies/planning', '11: Transportation-Established electric vehicle charging ready bylaws', '11: Transportation-Electric vehicle charging infrastructure investments', '11: Transportation-Streamlined hydrogen fuelling station permitting process', '11: Transportation-Required new and/or existing gasoline and card lock fuel stations to include zero-emission vehicle infrastructure development', '11: Transportation-Required green roads certification for any new or significantly modified existing roads', '11: Transportation-Not applicable\xa0', '11: Transportation-Other', '11: Transportation-Other (2)', '12: community-wide action -Complete, compact communities', '12: community-wide action -Organics diversion', '12: community-wide action -Circular economy or zero waste strategy', '12: community-wide action -Sustainable procurement policy', '12: community-wide action -Energy emission plans', '12: community-wide action -Renewable energy investments (e.g. district energy, waste heat recovery, biomass)', '12: community-wide action -Green/blue carbon sequestration', '12: community-wide action -Compliance carbon offset projects', '12: community-wide action -Voluntary carbon offset projects', '12: community-wide action -Bylaws updated to allow at least three units in all single-family zones', '12: community-wide action -Other', '12: community-wide action -Other (2)', '12: community-wide action -Not applicable', '12: Complete, Compact Communities - Rezoning', '12: Complete, Compact Communities - Smaller lots', '12: Complete, Compact Communities - Density bonuses', '12: Complete, Compact Communities - Secondary suites and laneway homes', '12: Complete, Compact Communities - Infill development', '12: Complete, Compact Communities - Urban containment boundaries', '12: Complete, Compact Communities - Official Community Plans', '12: Complete, Compact Communities - Regional Growth Strategies', '12: Complete, Compact Communities - Community Development Plans', '13: Resilience-\xa0Undertaking or completing a risk assessment or Hazard Risk Vulnerability Assessment (HRVA)', '13: Resilience-\xa0\xa0Addressing current and future climate risks through plans, adaptation measure implementation, programs, service delivery, asset management and/or other functions.', '13: Resilience-\xa0Collaboration with other communities on resilience planning/initiatives', '13: Resilience-\xa0Hydro climatological data collection', '13: Resilience-\xa0Monitoring climate risks (floods, wildfire, etc.)', '13: Resilience-\xa0Public engagement on climate risks and actions', '13: Resilience-\xa0\xa0Providing training (adaptation and mitigation skills)', '13: Resilience-\xa0Creation of policy/procedures to affect change (putting climate considerations into decision-making processes)', '13: Resilience-\xa0Creating data systems to support climate action', '13: Resilience-\xa0\xa0Utilizing natural assets/nature-based solutions', '13: Resilience-\xa0\xa0Developing emergency/hazard response plans', '13: Resilience-\xa0Not applicable', '13: Resilience-\xa0Other', '13: Resilience-\xa0Other (2)', '14: climate risk and vulnerability assessment', 'DELTEE -Please provide the link to the public assessment if available.', '14: No, but we are currently undertaking one and it will be complete in the next two years.', '14: No, we are not intending to undertake due to lack of financial capacity.', '14: No, we are not intending to undertake due to lack of staff and technical capacity.', '14: No, we are waiting for direction from the Provincial Government before undertaking an assessment.', '15:\xa0most significant climate hazards\xa0-Extreme heat and heat stress', '15:\xa0most significant climate hazards\xa0-Extreme heat and heat stress (2)', '15:\xa0most significant climate hazards\xa0-\xa0Extreme cold, snow and ice', '15:\xa0most significant climate hazards\xa0-\xa0Extreme cold, snow and ice (2)', '15:\xa0most significant climate hazards\xa0-\xa0Water shortages', '15:\xa0most significant climate hazards\xa0-Water shortages (2)', '15:\xa0most significant climate hazards\xa0-\xa0Wildfire', '15:\xa0most significant climate hazards\xa0-\xa0Wildfire (2)', '15:\xa0most significant climate hazards\xa0-Overland flooding', '15:\xa0most significant climate hazards\xa0-Overland flooding (2)', '15:\xa0most significant climate hazards\xa0-Coastal flooding, storm surge events and/or other coastal hazards', '15:\xa0most significant climate hazards\xa0-Coastal flooding, storm surge events and/or other coastal hazards (2)', '15:\xa0most significant climate hazards\xa0-Wind, rain, and other storm events', '15:\xa0most significant climate hazards\xa0-Wind, rain, and other storm events (2)', '15:\xa0most significant climate hazards\xa0-Ecological impacts (examples of ecological impacts include biodiversity loss and erosion)', '15:\xa0most significant climate hazards\xa0-\xa0Ecological impacts (examples of ecological impacts include biodiversity loss and erosion) (2)', '15:\xa0most significant climate hazards\xa0-Cultural impacts\xa0(examples of cultural impacts include threats to identities, languages, and livelihoods)\xa0', '15:\xa0most significant climate hazards\xa0-Cultural impacts\xa0(examples of cultural impacts include threats to identities, languages, and livelihoods)\xa0(2)', '15:\xa0most significant climate hazards\xa0-Human health impacts', '15:\xa0most significant climate hazards\xa0-\xa0Human health impacts (2)', '15:\xa0most significant climate hazards\xa0-\xa0Not applicable/no hazards', '15:\xa0most significant climate hazards\xa0-Not sure', '15:\xa0most significant climate hazards\xa0-Other', '15:\xa0most significant climate hazards\xa0-\xa0Other (2)', '16:\xa0info needed for impacts-Local observations and/or Indigenous knowledge', '16:\xa0info needed for impacts-Localized climate modelling and projected scenarios', '16:\xa0info needed for impacts-Assessment of potential community impacts', '16:\xa0info needed for impacts-Assessment of community vulnerabilities', '16:\xa0info needed for impacts-Risk assessment of hazards', '16:\xa0info needed for impacts-Mapping of climate change impacts and hazards', '16:\xa0info needed for impacts-Demographic information', '16:\xa0info needed for impacts-Projected development', '16:\xa0info needed for impacts-Adaptation planning information', '16:\xa0info needed for impacts-Technical expertise to implement solutions', '16:\xa0info needed for impacts-Community/stakeholder engagement and support', '16:\xa0info needed for impacts-Information on partnership opportunities', '16:\xa0info needed for impacts-Examples of actions taken by other communities', '16:\xa0info needed for impacts-Not sure', '16:\xa0info needed for impacts-Other', '16:\xa0info needed for impacts-Other (2)', '17: most vulnerable to impacts-Low-income households', '17: most vulnerable to impacts-Indigenous Peoples', '17: most vulnerable to impacts-Racialized communities', '17: most vulnerable to impacts-Newcomers to Canada (immigrants and refugees)', '17: most vulnerable to impacts-People experiencing homelessness', '17: most vulnerable to impacts-Seniors', '17: most vulnerable to impacts-Women and girls', '17: most vulnerable to impacts-Persons with disabilities', '17: most vulnerable to impacts-LGBTQIA2S+: Lesbian, Gay, Bisexual, Transgender, Queer or Questioning, Intersex, Asexual, Two-Spirit, and additional sexual orientations and gender identities', '17: most vulnerable to impacts-Not sure', '17: most vulnerable to impacts-Other', '17: most vulnerable to impacts-Other (2)', '18: associated adaptation measures-Extreme heat and heat stress', '18: associated adaptation measures-Extreme cold, snow and iceAdaptation measure', '18: associated adaptation measures-Water shortagesAdaptation measure', '18: associated adaptation measures-WildfireAdaptation measure', '18: associated adaptation measures-Overland floodingAdaptation measure', '18: associated adaptation measures-Coastal flooding, storm surge events and/or other coastal hazardsAdaptation measure', '18: associated adaptation measures-Wind, rain, and other storm eventsAdaptation measure', '18: associated adaptation measures-Ecological impactsAdaptation measure', '18: associated adaptation measures-Human health impactsAdaptation measure', '18: associated adaptation measures-Cultural impactsAdaptation measure', '18: associated adaptation measures-OtherAdaptation measure', '19:\xa0 equitable access to and distribution-By collecting and analyzing disaggregated and/or spatial data on the impacts of climate policy and change.', '19:\xa0 equitable access to and distribution-By engaging with equity seeking groups/frontline communities most impacted by climate policy and change.', '19:\xa0 equitable access to and distribution-By designing and implementing climate actions that remove barriers to participation in planning and programs faced by equity seeking groups/frontline communities most impacted by climate change.', '19:\xa0 equitable access to and distribution-There are no specific measures in place to ensure equitable access to and distribution of opportunities and benefits.', '19:\xa0 equitable access to and distribution-Not sure how to integrate equity into our climate action work.', '19:\xa0 equitable access to and distribution-Not sure if equity is being integrated into our climate action work.', '20: LGCAP funding for year one-Staffing', '20: LGCAP funding for year one-Staffing (2)', '20: LGCAP funding for year one-Climate study', '20: LGCAP funding for year one-Climate study (2)', '20: LGCAP funding for year one-Energy study', '20: LGCAP funding for year one-Energy study (2)', '20: LGCAP funding for year one-Asset management', '20: LGCAP funding for year one-Asset management (2)', '20: LGCAP funding for year one-Risk and vulnerability assessment', '20: LGCAP funding for year one-Risk and vulnerability assessment (2)', '20: LGCAP funding for year one-Emergency response planning', '20: LGCAP funding for year one-Emergency response planning (2)', '20: LGCAP funding for year one-Vulnerability and risk reduction strategy', '20: LGCAP funding for year one-Vulnerability and risk reduction strategy (2)', '20: LGCAP funding for year one-Climate finance planning', '20: LGCAP funding for year one-Climate finance planning (2)', '20: LGCAP funding for year one-Climate engagement', '20: LGCAP funding for year one-Climate engagement (2)', '20: LGCAP funding for year one-Resilient infrastructure', '20: LGCAP funding for year one-Resilient infrastructure (2)', '20: LGCAP funding for year one-Green infrastructure', '20: LGCAP funding for year one-Green infrastructure (2)', '20: LGCAP funding for year one-Natural assets evaluation and accounting', '20: LGCAP funding for year one-Natural assets evaluation and accounting (2)', '20: LGCAP funding for year one-Buildings initiatives', '20: LGCAP funding for year one-Buildings initiatives (2)', '20: LGCAP funding for year one-Transportation initiatives', '20: LGCAP funding for year one-Transportation initiatives (2)', '20: LGCAP funding for year one-Community-wide initiatives', '20: LGCAP funding for year one-Community-wide initiatives (2)', '20: LGCAP funding for year one-Put in reserve for future project', '20: LGCAP funding for year one-Put in reserve for future project (2)', '20: LGCAP funding for year one-Corporate emissions inventory measurement and reporting', '20: LGCAP funding for year one-Corporate emissions inventory measurement and reporting (2)', '20: LGCAP funding for year one-Leveraging funds from other sources/ grant stacking', '20: LGCAP funding for year one-Leveraging funds from other sources/ grant stacking (2)', '20: LGCAP funding for year one-Other', '20: LGCAP funding for year one-Other (2)', '20: LGCAP funding for year one-Resilient Infrastructure - Buildings', '20: LGCAP funding for year one-Resilient Infrastructure - Transportation', '20: LGCAP funding for year one-Resilient Infrastructure -Municipal infrastructure (wastewater treatment facilities, etc.)', '20: LGCAP funding for year one-Resilient Infrastructure - Energy systems', '20: LGCAP funding for year one-Green Infrastructure - Parks & other green space(s)', '20: LGCAP funding for year one-Green Infrastructure - Community forest(s)', '20: LGCAP funding for year one-Green Infrastructure -Community food systems', '20: LGCAP funding for year one-Green Infrastructure - Green streets/alleys/corridors', '20: LGCAP funding for year one-Green Infrastructure - Green roof(s) or wall(s)', '20: LGCAP funding for year one-Green Infrastructure - Permeable surfaces or substrates', '20: LGCAP funding for year one-Green Infrastructure - Stormwater management', '20: LGCAP funding for year one-Green Infrastructure - Wetlands', '20: LGCAP funding for year one-Buildings - Zero-carbon new construction requirement', '20: LGCAP funding for year one-Buildings -Highest efficiency standards for new space and water heating equipment', '20: LGCAP funding for year one-Buildings - Enhancing energy efficiency programs', '20: LGCAP funding for year one-Buildings - Step c

In [9]:
climate_plan_subset.columns = climate_plan_subset.columns.str.replace(r'\s+', ' ', regex=True)
# Then use the normal name:
climate_plan_subset['Has_Climate_Action_Plan'] = climate_plan_subset['2: Climate Action Plan'].map({'Yes': 1, 'No': 0})
climate_plan_subset['Climate_Emergency'] = climate_plan_subset['3: climate emergency'].map({'Yes': 1, 'No': 0})
climate_plan_subset['Reports_Corporate_Emissions'] = climate_plan_subset['5: reported corporate GHG emissions'].map({'Yes': 1, 'No': 0, 'No, but for a past year. (Please enter most recent year completed: YYYY)': 1})
#if either 6: measured and reported community-wide emissions in the past? or '5: reported corporate GHG emissions' is yes, then set Community_GHG_tracking to 1
climate_plan_subset['Community_GHG_tracking'] = climate_plan_subset['6: community-wide GHG emissions'].map({'Yes': 1, 'No': 0, 'In-progress': 1})
climate_plan_subset.loc[climate_plan_subset['6: measured and reported community-wide emissions in the past?'] == 'Yes', 'Community_GHG_tracking'] = 1
climate_plan_subset['Net_Zero_Or_Carbon_Neutral_Target'] = climate_plan_subset['8: net-zero or carbon-neutral emissions target?'].map(
    {'Yes: Net-zero (Net-zero refers to a jurisdiction achieving a balance between greenhouse gas emissions produced and removed from the atmosphere (e.g. planting trees or using carbon capture technologies))': 1, 
     'Yes: Carbon neutral (Carbon neutral refers to a jurisdiction achieving a state of no net carbon dioxide emissions being released into the atmosphere (e.g. Reducing emissions as far as practical and purchasing offsets or other similar mechanisms))': 1,
     'No': 0})

In [10]:
climate_plan_subset['No_Staff_Capacity_For_GHG_Tracking'] = climate_plan_subset[
    "6: No, we do not measure and report community-wide emissions data due to lack of staff and technical capacity."
    ].map({"No, we do not measure and report community-wide emissions data due to lack of staff and technical capacity.": 1, np.nan: 0})

climate_plan_subset['No_Financial_Capacity_For_GHG_Tracking'] = climate_plan_subset[
    "6: No, we do not measure and report community-wide emissions data due to lack of financial capacity."
    ].map({"No, we do not measure and report community-wide emissions data due to lack of financial capacity.": 1, np.nan: 0})

climate_plan_subset['Lack_Of_Jursidiction_Climate_Action'] = climate_plan_subset[
    "4: Challenges.Lack of jurisdiction."].map({"Lack of jurisdiction.": 1, np.nan: 0})

climate_plan_subset['Lack_Of_Staff_Capacity_Climate_Action'] = climate_plan_subset[
    "4: Challenges.Lack of staff capacity or expertise."].map({"Lack of staff capacity or expertise.": 1, np.nan: 0})

climate_plan_subset['Lack_Of_Financial_Capacity_Climate_Action'] = climate_plan_subset[
    "4: Challenges.Lack of financial resources."].map({"Lack of financial resources.": 1, np.nan: 0})

climate_plan_subset['Lack_Of_Information_Climate_Action'] = climate_plan_subset[
    "4: Challenges.Lack of data or information."].map({"Lack of data or information.": 1, np.nan: 0})

climate_plan_subset['Lack_Of_Political_Support_Climate_Action'] = climate_plan_subset[
    "4: Challenges.Lack of local political support."].map({"Lack of local political support.": 1, np.nan: 0})

climate_plan_subset['Lack_Of_Provincial_Federal_Support_Climate_Action'] = climate_plan_subset[
    "4: Challenges.Lack of provincial or federal government support or collaboration."].map({"Lack of provincial or federal government support or collaboration.": 1, np.nan: 0})

In [11]:
climate_plan_subset.to_csv(os.path.join('..','..','data','processed','climate_action_plans_matched.csv'), index=False)

In [12]:
climate_plan_subset.head()

,Year,Org Unit,MUNI,RD,EDR,1: FTEs,2: Climate Action Plan,"2: addressing mitigation, adaptation and/or energy use",2: addressing mitigation and adaptation,2: addressing mitigation and energy,...,Community_GHG_tracking,Net_Zero_Or_Carbon_Neutral_Target,No_Staff_Capacity_For_GHG_Tracking,No_Financial_Capacity_For_GHG_Tracking,Lack_Of_Jursidiction_Climate_Action,Lack_Of_Staff_Capacity_Climate_Action,Lack_Of_Financial_Capacity_Climate_Action,Lack_Of_Information_Climate_Action,Lack_Of_Political_Support_Climate_Action,Lack_Of_Provincial_Federal_Support_Climate_Action
0,2022,5941005,One Hundred Mile House,Cariboo Regional District,Cariboo,0.25,Yes,NaN,NaN,NaN,...,1,0,0,0,1,1,0,1,0,0
1,2022,5909052,Abbotsford,Fraser Valley Regional District,Mainland/Southwest,5.50,No,NaN,NaN,NaN,...,1,0,0,0,0,1,1,0,0,1
3,2022,5943008,Alert Bay,Mount Waddington Regional District,Vancouver Island/Coast,0.10,No,NaN,NaN,NaN,...,0,0,1,0,0,1,1,1,0,0
4,2022,5915038,Anmore,Metro Vancouver Regional District,Mainland/Southwest,0.00,No,NaN,NaN,NaN,...,0,0,1,1,0,1,1,0,0,0
5,2022,5937028,Armstrong,North Okanagan Regional District,Thompson/Okanagan,0.00,No,NaN,NaN,NaN,...,0,0,1,0,0,1,1,1,0,0

In [13]:
#print all column names 
print(climate_plan_subset.columns.tolist())

['Year', 'Org Unit', 'MUNI', 'RD', 'EDR', '1: FTEs', '2: Climate Action Plan', '2: addressing mitigation, adaptation and/or energy use', '2: addressing mitigation and adaptation', '2: addressing mitigation and energy', '2: addressing adaptation and energy', '2: Standalone mitigation plan', '2: Standalone adaptation plan', '2: Standalone energy-related plan', "2: Don't know", 'Please include a link to the document or webpage if available.', '2: No, but we are currently undertaking one and it will be completed in the next two years.', '2: No, we are not intending to undertake one due to lack of financial capacity.', '2: No, we are not intending to undertake one due to lack of expertise or technical capacity.', '3: climate emergency', '4: Challenges.Lack of jurisdiction.', '4: Challenges.Lack of staff capacity or expertise.', '4: Challenges.Lack of financial resources.', '4: Challenges.Lack of data or information.', '4: Challenges.Lack of local political support.', '4: Challenges.Lack of provincial or federal government support or collaboration.', '4: Challenges.Other.', '4: Challenges.Other. (2)', '5: reported corporate GHG emissions', '5: No, but for a past year. (Please enter most recent year completed: YYYY)', '5: directly delivered services (tCO2e)', '5: contracted services (tCO2e)', '5: total corporate GHG emissions', '5: facilities', '5: mobile sources. ', 'Please provide the link to the public report if available.', '5: No, due to lack of staff and technical capacity.', '5: No, due to lack of financial resources.', '5: No, due to lack of awareness regarding which GHG accounting tools are available.', '5: No, corporate emissions are measured but not reported.', '5: Measurement is in-progress.', '5: Corporate inventory is not developed annually. ', '6: community-wide GHG emissions', '6: transportation sector emissions in tonnes of CO2e for 2022.', '6: community-wide buildings sector emissions in tonnes of CO2e for 2022.', '6: community-wide solid waste sector emissions in tonnes of CO2e for 2022.', '6: No, community GHG emissions were not reported because the 2022 Provincial Community Energy and Emissions Inventory data has not been released.', '6: No, community GHG emissions were not reported because the 2022 Provincial Community Energy and Emissions Inventory does not report transportation data.', '6: No, we do not measure and report community-wide emissions data due to lack of financial capacity.', '6: No, we do not measure and report community-wide emissions data due to lack of staff and technical capacity.', '6: No, we do not measure and report community-wide emissions annually.', '6: No, we do not measure and report community-wide emissions annually (2)', '6: measured and reported community-wide emissions in the past?', 'When was the last year your community or Nation reported its community-wide emissions and what is the interval for reporting (ex. every 5 years)?', 'For the 2022 calendar year, did your community use raw data from the Community Energy and Emissions Inventory initiative to calculate community-wide emissions?', '7: target(s) 2030 Reduction (format: e.g., 40%) ', '7: target(s).2030 Baseline Year (format: 2007)', '7: target(s).2040Reduction (format: e.g., 40%) ', "Question 7: Currently, the Province's legislated GHG emission reduction targets are 40% by 2030, 60% by 2040 and 80% by 2050, relative to 2007. Please state your local government or Nation’s target(s).2040Baseline Year (format: 2007)", '7: target(s).2050Reduction (format: e.g., 40%) ', "Question 7: Currently, the Province's legislated GHG emission reduction targets are 40% by 2030, 60% by 2040 and 80% by 2050, relative to 2007. Please state your local government or Nation’s target(s).2050Baseline Year (format: 2007)", '7: target open years', '8: net-zero or carbon-neutral emissions target?', '9: Supporting Indicators -Private dwellings by structural type', '9: Supporting Indicators - Floor area: Average floor area by building category and era', '9: Supporting Indicators - Residential density: Population and dwelling units per "net" land area', '9: Supporting Indicators -Commute by mode: Employed labour force by mode of commute', '9: Supporting Indicators - Greenspace: Land area that is parks and protected greenspace', '9: Supporting Indicators - Walk score: Proximity to services', '9: Supporting Indicators - Proximity to transit: Persons, dwelling units and employment within walking distance of a "quality" transit stop/line', '9: Supporting Indicators - Other', '9: Supporting Indicators - Other (2)', 'Optional: Please provide any further comments you wish to share on community-wide emissions measurement and reporting here.', '10: Buildings- Zero-carbon new construction', '10: Buildings- Highest efficiency standards for new space and water heating equipment', '10: Buildings- Topping up Provincial energy efficiency programs', '10: Buildings- Step Code adoption', '10: Buildings- Zero Carbon Step Code', '10: Buildings- Zero-carbon heating requirement', '10: Buildings- Net zero buildings commitments', '10: Buildings- Efficiency upgrades to public buildings', '10: Buildings- Demand-side management ', '10: Buildings- Not applicable', '10: Buildings- Other', '10: Buildings- Other (2)', 'Please enter date effective for zero-carbon new construction requirement.', '11: Transportation-Demand-side management to reduce distance travelled (single-occupancy vehicle commute reduction programs, parking disincentives)', '11: Transportation-Improving or expanding public transportation', '11: Transportation-Mode shift targets in Official Community Plan, Regional Growth Strategy or other guiding document', '11: Transportation-Established personal transportation target goals, and measures to reach them, in annual reports – must include target goals for vehicle kilometre reduction, mode share for active transportation and zero-emission vehicles – and report on progress', '11: Transportation-Established commercial transportation target goals, and measures to reach them, in annual reports – must include target goals for vehicle kilometre reduction, mode share for energy efficient commercial transportation and zero-emission vehicles – report on progress', '11: Transportation-Implemented zero-emission vehicle first procurement policy for all local government on and off-road vehicles purchases.', '11: Transportation-Implemented a zero-emission vehicle preference or requirement for contracted work from a service provider', '11: Transportation-Bylaws updated to prioritize energy efficient transportation hierarchy (i.e. pedestrians first) ', '11: Transportation-Revising existing bylaws or implementing new ones to support active transportation', '11: Transportation-Active transportation planning', '11: Transportation-Active transportation infrastructure investments', '11: Transportation-Electric vehicle charging studies/planning', '11: Transportation-Established electric vehicle charging ready bylaws', '11: Transportation-Electric vehicle charging infrastructure investments', '11: Transportation-Streamlined hydrogen fuelling station permitting process', '11: Transportation-Required new and/or existing gasoline and card lock fuel stations to include zero-emission vehicle infrastructure development', '11: Transportation-Required green roads certification for any new or significantly modified existing roads', '11: Transportation-Not applicable ', '11: Transportation-Other', '11: Transportation-Other (2)', '12: community-wide action -Complete, compact communities', '12: community-wide action -Organics diversion', '12: community-wide action -Circular economy or zero waste strategy', '12: community-wide action -Sustainable procurement policy', '12: community-wide action -Energy emission plans', '12: community-wide action -Renewable energy investments (e.g. district energy, waste heat recovery, biomass)', '12: community-wide action -Green/blue carbon sequestration', '12: community-wide action -Compliance carbon offset projects', '12: community-wide action -Voluntary carbon offset projects', '12: community-wide action -Bylaws updated to allow at least three units in all single-family zones', '12: community-wide action -Other', '12: community-wide action -Other (2)', '12: community-wide action -Not applicable', '12: Complete, Compact Communities - Rezoning', '12: Complete, Compact Communities - Smaller lots', '12: Complete, Compact Communities - Density bonuses', '12: Complete, Compact Communities - Secondary suites and laneway homes', '12: Complete, Compact Communities - Infill development', '12: Complete, Compact Communities - Urban containment boundaries', '12: Complete, Compact Communities - Official Community Plans', '12: Complete, Compact Communities - Regional Growth Strategies', '12: Complete, Compact Communities - Community Development Plans', '13: Resilience- Undertaking or completing a risk assessment or Hazard Risk Vulnerability Assessment (HRVA)', '13: Resilience- Addressing current and future climate risks through plans, adaptation measure implementation, programs, service delivery, asset management and/or other functions.', '13: Resilience- Collaboration with other communities on resilience planning/initiatives', '13: Resilience- Hydro climatological data collection', '13: Resilience- Monitoring climate risks (floods, wildfire, etc.)', '13: Resilience- Public engagement on climate risks and actions', '13: Resilience- Providing training (adaptation and mitigation skills)', '13: Resilience- Creation of policy/procedures to affect change (putting climate considerations into decision-making processes)', '13: Resilience- Creating data systems to support climate action', '13: Resilience- Utilizing natural assets/nature-based solutions', '13: Resilience- Developing emergency/hazard response plans', '13: Resilience- Not applicable', '13: Resilience- Other', '13: Resilience- Other (2)', '14: climate risk and vulnerability assessment', 'DELTEE -Please provide the link to the public assessment if available.', '14: No, but we are currently undertaking one and it will be complete in the next two years.', '14: No, we are not intending to undertake due to lack of financial capacity.', '14: No, we are not intending to undertake due to lack of staff and technical capacity.', '14: No, we are waiting for direction from the Provincial Government before undertaking an assessment.', '15: most significant climate hazards -Extreme heat and heat stress', '15: most significant climate hazards -Extreme heat and heat stress (2)', '15: most significant climate hazards - Extreme cold, snow and ice', '15: most significant climate hazards - Extreme cold, snow and ice (2)', '15: most significant climate hazards - Water shortages', '15: most significant climate hazards -Water shortages (2)', '15: most significant climate hazards - Wildfire', '15: most significant climate hazards - Wildfire (2)', '15: most significant climate hazards -Overland flooding', '15: most significant climate hazards -Overland flooding (2)', '15: most significant climate hazards -Coastal flooding, storm surge events and/or other coastal hazards', '15: most significant climate hazards -Coastal flooding, storm surge events and/or other coastal hazards (2)', '15: most significant climate hazards -Wind, rain, and other storm events', '15: most significant climate hazards -Wind, rain, and other storm events (2)', '15: most significant climate hazards -Ecological impacts (examples of ecological impacts include biodiversity loss and erosion)', '15: most significant climate hazards - Ecological impacts (examples of ecological impacts include biodiversity loss and erosion) (2)', '15: most significant climate hazards -Cultural impacts (examples of cultural impacts include threats to identities, languages, and livelihoods) ', '15: most significant climate hazards -Cultural impacts (examples of cultural impacts include threats to identities, languages, and livelihoods) (2)', '15: most significant climate hazards -Human health impacts', '15: most significant climate hazards - Human health impacts (2)', '15: most significant climate hazards - Not applicable/no hazards', '15: most significant climate hazards -Not sure', '15: most significant climate hazards -Other', '15: most significant climate hazards - Other (2)', '16: info needed for impacts-Local observations and/or Indigenous knowledge', '16: info needed for impacts-Localized climate modelling and projected scenarios', '16: info needed for impacts-Assessment of potential community impacts', '16: info needed for impacts-Assessment of community vulnerabilities', '16: info needed for impacts-Risk assessment of hazards', '16: info needed for impacts-Mapping of climate change impacts and hazards', '16: info needed for impacts-Demographic information', '16: info needed for impacts-Projected development', '16: info needed for impacts-Adaptation planning information', '16: info needed for impacts-Technical expertise to implement solutions', '16: info needed for impacts-Community/stakeholder engagement and support', '16: info needed for impacts-Information on partnership opportunities', '16: info needed for impacts-Examples of actions taken by other communities', '16: info needed for impacts-Not sure', '16: info needed for impacts-Other', '16: info needed for impacts-Other (2)', '17: most vulnerable to impacts-Low-income households', '17: most vulnerable to impacts-Indigenous Peoples', '17: most vulnerable to impacts-Racialized communities', '17: most vulnerable to impacts-Newcomers to Canada (immigrants and refugees)', '17: most vulnerable to impacts-People experiencing homelessness', '17: most vulnerable to impacts-Seniors', '17: most vulnerable to impacts-Women and girls', '17: most vulnerable to impacts-Persons with disabilities', '17: most vulnerable to impacts-LGBTQIA2S+: Lesbian, Gay, Bisexual, Transgender, Queer or Questioning, Intersex, Asexual, Two-Spirit, and additional sexual orientations and gender identities', '17: most vulnerable to impacts-Not sure', '17: most vulnerable to impacts-Other', '17: most vulnerable to impacts-Other (2)', '18: associated adaptation measures-Extreme heat and heat stress', '18: associated adaptation measures-Extreme cold, snow and iceAdaptation measure', '18: associated adaptation measures-Water shortagesAdaptation measure', '18: associated adaptation measures-WildfireAdaptation measure', '18: associated adaptation measures-Overland floodingAdaptation measure', '18: associated adaptation measures-Coastal flooding, storm surge events and/or other coastal hazardsAdaptation measure', '18: associated adaptation measures-Wind, rain, and other storm eventsAdaptation measure', '18: associated adaptation measures-Ecological impactsAdaptation measure', '18: associated adaptation measures-Human health impactsAdaptation measure', '18: associated adaptation measures-Cultural impactsAdaptation measure', '18: associated adaptation measures-OtherAdaptation measure', '19: equitable access to and distribution-By collecting and analyzing disaggregated and/or spatial data on the impacts of climate policy and change.', '19: equitable access to and distribution-By engaging with equity seeking groups/frontline communities most impacted by climate policy and change.', '19: equitable access to and distribution-By designing and implementing climate actions that remove barriers to participation in planning and programs faced by equity seeking groups/frontline communities most impacted by climate change.', '19: equitable access to and distribution-There are no specific measures in place to ensure equitable access to and distribution of opportunities and benefits.', '19: equitable access to and distribution-Not sure how to integrate equity into our climate action work.', '19: equitable access to and distribution-Not sure if equity is being integrated into our climate action work.', '20: LGCAP funding for year one-Staffing', '20: LGCAP funding for year one-Staffing (2)', '20: LGCAP funding for year one-Climate study', '20: LGCAP funding for year one-Climate study (2)', '20: LGCAP funding for year one-Energy study', '20: LGCAP funding for year one-Energy study (2)', '20: LGCAP funding for year one-Asset management', '20: LGCAP funding for year one-Asset management (2)', '20: LGCAP funding for year one-Risk and vulnerability assessment', '20: LGCAP funding for year one-Risk and vulnerability assessment (2)', '20: LGCAP funding for year one-Emergency response planning', '20: LGCAP funding for year one-Emergency response planning (2)', '20: LGCAP funding for year one-Vulnerability and risk reduction strategy', '20: LGCAP funding for year one-Vulnerability and risk reduction strategy (2)', '20: LGCAP funding for year one-Climate finance planning', '20: LGCAP funding for year one-Climate finance planning (2)', '20: LGCAP funding for year one-Climate engagement', '20: LGCAP funding for year one-Climate engagement (2)', '20: LGCAP funding for year one-Resilient infrastructure', '20: LGCAP funding for year one-Resilient infrastructure (2)', '20: LGCAP funding for year one-Green infrastructure', '20: LGCAP funding for year one-Green infrastructure (2)', '20: LGCAP funding for year one-Natural assets evaluation and accounting', '20: LGCAP funding for year one-Natural assets evaluation and accounting (2)', '20: LGCAP funding for year one-Buildings initiatives', '20: LGCAP funding for year one-Buildings initiatives (2)', '20: LGCAP funding for year one-Transportation initiatives', '20: LGCAP funding for year one-Transportation initiatives (2)', '20: LGCAP funding for year one-Community-wide initiatives', '20: LGCAP funding for year one-Community-wide initiatives (2)', '20: LGCAP funding for year one-Put in reserve for future project', '20: LGCAP funding for year one-Put in reserve for future project (2)', '20: LGCAP funding for year one-Corporate emissions inventory measurement and reporting', '20: LGCAP funding for year one-Corporate emissions inventory measurement and reporting (2)', '20: LGCAP funding for year one-Leveraging funds from other sources/ grant stacking', '20: LGCAP funding for year one-Leveraging funds from other sources/ grant stacking (2)', '20: LGCAP funding for year one-Other', '20: LGCAP funding for year one-Other (2)', '20: LGCAP funding for year one-Resilient Infrastructure - Buildings', '20: LGCAP funding for year one-Resilient Infrastructure - Transportation', '20: LGCAP funding for year one-Resilient Infrastructure -Municipal infrastructure (wastewater treatment facilities, etc.)', '20: LGCAP funding for year one-Resilient Infrastructure - Energy systems', '20: LGCAP funding for year one-Green Infrastructure - Parks & other green space(s)', '20: LGCAP funding for year one-Green Infrastructure - Community forest(s)', '20: LGCAP funding for year one-Green Infrastructure -Community food systems', '20: LGCAP funding for year one-Green Infrastructure - Green streets/alleys/corridors', '20: LGCAP funding for year one-Green Infrastructure - Green roof(s) or wall(s)', '20: LGCAP funding for year one-Green Infrastructure - Permeable surfaces or substrates', '20: LGCAP funding for year one-Green Infrastructure - Stormwater management', '20: LGCAP funding for year one-Green Infrastructure - Wetlands', '20: LGCAP funding for year one-Buildings - Zero-carbon new construction requirement', '20: LGCAP funding for year one-Buildings -Highest efficiency standards for new space and water heating equipment', '20: LGCAP funding for year one-Buildings - Enhancing energy efficiency programs', '20: LGCAP funding for year one-Buildings - Step code adoption', '20: LGCAP funding for year one-Buildings - Carbon pollution standard', '20: LGCAP funding for year one-Buildings - Zero-carbon heating requirement', '20: LGCAP funding for year one-Buildings - Net zero buildings commitments', '20: LGCAP funding for year one-Buildings - Efficiency upgrades to public buildings', '20: LGCAP funding

In [ ]:
import pandas as pd


# Instead of 13 binary variables:
climate_plan_subset['Climate_Action_Score'] = (
    climate_plan_subset['Has_Climate_Action_Plan'] + 
    climate_plan_subset['Climate_Emergency'] + 
    climate_plan_subset['Reports_Corporate_Emissions'] +
    climate_plan_subset['Net_Zero_Or_Carbon_Neutral_Target'] +
    climate_plan_subset['Community_GHG_tracking']
)  # 0-5 scale

climate_plan_subset['Climate_Action_N_Barriers'] = (
    climate_plan_subset['No_Staff_Capacity_For_GHG_Tracking'] +
    climate_plan_subset['No_Financial_Capacity_For_GHG_Tracking'] +
    climate_plan_subset['Lack_Of_Staff_Capacity_Climate_Action'] +
    climate_plan_subset['Lack_Of_Financial_Capacity_Climate_Action'] +
    climate_plan_subset['Lack_Of_Information_Climate_Action'] +
    climate_plan_subset['Lack_Of_Political_Support_Climate_Action'] +
    climate_plan_subset['Lack_Of_Provincial_Federal_Support_Climate_Action'] +
    climate_plan_subset['Lack_Of_Jursidiction_Climate_Action']
)  # Count of barriers


# List all your binary/metric columns (the ones you want to convert to tidy)
columns = [
    'Has_Climate_Action_Plan',
    'Climate_Emergency',
    'Reports_Corporate_Emissions',
    'Community_GHG_tracking',
    'Net_Zero_Or_Carbon_Neutral_Target',
    'No_Staff_Capacity_For_GHG_Tracking',
    'No_Financial_Capacity_For_GHG_Tracking',
    'Lack_Of_Jursidiction_Climate_Action',
    'Lack_Of_Staff_Capacity_Climate_Action',
    'Lack_Of_Financial_Capacity_Climate_Action',
    'Lack_Of_Information_Climate_Action',
    'Lack_Of_Political_Support_Climate_Action',
    'Lack_Of_Provincial_Federal_Support_Climate_Action',
    'Climate_Action_N_Barriers',
    'Climate_Action_Score'
]

# Melt: convert wide to tidy (one row per municipality × metric)
climate_plan_tidy = climate_plan_subset[['MUNI'] + columns].melt(
    id_vars=['MUNI'],
    value_vars=columns,
    var_name='Metric',
    value_name='Value'
).copy()



# Rename and add columns to match tidy format
climate_plan_tidy = climate_plan_tidy.rename(columns={'MUNI': 'Municipality_Name'})
climate_plan_tidy['Year'] = 2021
climate_plan_tidy['Unit'] = 'Yes/No'

# Update units for summary scores
climate_plan_tidy.loc[climate_plan_tidy['Metric'] == 'Climate_Action_Score', 'Unit'] = 'count out of 5'
climate_plan_tidy.loc[climate_plan_tidy['Metric'] == 'Climate_Action_N_Barriers', 'Unit'] = 'count out of 8'


# Reorder to standard tidy column order
climate_plan_tidy = climate_plan_tidy[['Municipality_Name', 'Year', 'Metric', 'Value', 'Unit']]

# Save to CSV
climate_plan_tidy.to_csv(os.path.join('..','..','data','processed','tidy_climate_action.csv'), index=False)

print(f"Created {len(climate_plan_tidy)} tidy rows ({len(climate_plan_subset)} municipalities × {len(columns)} metrics)")
print("\nFirst few rows:")
display(climate_plan_tidy.tail(10))

Created 2205 tidy rows (147 municipalities × 15 metrics)

First few rows:

     Municipality_Name  Year                Metric  Value            Unit
2195         Vancouver  2021  Climate_Action_Score      5  count out of 5
2196        Vanderhoof  2021  Climate_Action_Score      0  count out of 5
2197            Vernon  2021  Climate_Action_Score      4  count out of 5
2198          Victoria  2021  Climate_Action_Score      4  count out of 5
2199        View Royal  2021  Climate_Action_Score      5  count out of 5
2200          Warfield  2021  Climate_Action_Score      1  count out of 5
2201    West Vancouver  2021  Climate_Action_Score      5  count out of 5
2202          Whistler  2021  Climate_Action_Score      4  count out of 5
2203        White Rock  2021  Climate_Action_Score      2  count out of 5
2204     Williams Lake  2021  Climate_Action_Score      0  count out of 5